#!/bin/sh -x
# $Id$
# Alexey Munishkin (amunishk)
# Diem Phuong Chau (dhchau)
javac exit1.java
echo Main-class: exit1 >Manifest
jar cvfm exit1 Manifest exit1.class
yes | rm -i Manifest exit1.class
chmod +x exit1
